# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('primer_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=10)),
                ('exon', models.CharField(max_length=4)),
                ('direction', models.CharField(max_length=1)),
                ('seq', models.CharField(max_length=30)),
            ],
        ),
    ]
