# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerdb', '0002_auto_20170209_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='direction',
            field=models.CharField(choices=[('F', 'F'), ('R', 'R')], max_length=1),
        ),
        migrations.AlterField(
            model_name='primer',
            name='exon',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
